#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

# we want to migrate from 1.0.5 when the postgres password was default and no secrets were created

if [[ ! -f ~/.config/state/secrets/passwords.env ]]; then
    ../bin/create-secrets
    source ~/.config/state/secrets/passwords.env
    # change the password of the postgres user
    podman exec -ti postgresql-app sh -c "PGPASSWORD=${POSTGRES_PASSWORD} psql -U postgres -d postgres -c \"ALTER USER postgres WITH PASSWORD '${POSTGRES_PASSWORD}';\""
fi
